"""Module providing the constants"""

COLUMN_1 = 6
COLUMN_2 = 20
COLUMN_3 = 25
COLUMN_4 = 35
COLUMN_5 = 12
COLUMN_6 = 40
SPAN = COLUMN_1 + COLUMN_2 + COLUMN_3 + COLUMN_4 + COLUMN_5 + COLUMN_6 + 5
FIELD = SPAN - COLUMN_1 - 1
INDENT = " " * COLUMN_1
HEADER = f"|{'#':^{COLUMN_1}}|{'FULLNAME':^{COLUMN_2}}|{'EMAIL':^{COLUMN_3}}|{'PHONES':^{COLUMN_4}}|{'BIRTHDAY':^{COLUMN_5}}|{'ADDRESS':^{COLUMN_6}}|"
SKIPPER = f"|{INDENT}|{'Operation skipped':<{FIELD}}|"
SEPARATOR = "-" * (SPAN + 2)
